# build environment
FROM node:16.13.2 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install -g npm@9.6.2 --registry=https://registry.npm.taobao.org
RUN npm install --silent --unsafe-perm=true --allow-root --legacy-peer-deps --registry=https://registry.npm.taobao.org
RUN npm install -g @vue/cli --registry=https://registry.npm.taobao.org
COPY . /app
RUN npm install --registry=https://registry.npm.taobao.org
RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
